apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: backbone
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "garuda.labels" . | nindent 4 }}
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "backbone",
      "type": "bridge",
      "bridge": "backbone",
      "isGateway": false,
      "ipMasq": false,
      "ipam": {
        "type": "host-local",
        "dataDir": "/var/run/cni/backbone",
        "ranges": [[{ "subnet": {{ .Values.backboneSubnet | quote }} }]]
      }
    }
