---
collections:
  - name: community.general
    version: ">=8.0.0"
  - name: community.routeros
    version: ">=2.11.0"
  - name: ansible.netcommon
    version: ">=5.0.0"
  - name: community.docker
    version: ">=4.0.0"
